# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    #driver: "gd"
    filter_sets:
        mini:
            quality: 75
            filters:
                thumbnail: { size: [100, 75], mode: outbound }
        thumb:
            quality: 75
            filters:
                thumbnail: { size: [360, 230], mode: outbound }
        medium:
            quality: 75
            filters:
                thumbnail: { size: [360, 230], mode: outbound }
        large:
            quality: 75
            filters:
                thumbnail: { size: [630, 470], mode: outbound }

        card:
            quality: 75
            filters:
                dim: [1000, 564]
                thumbnail: { size: [330, 185], mode: outbound }


        carousel:
            quality: 75
            filters:
                fixed:
                    width: 650
                    heigth: 500
