vich_uploader:
    db_driver: orm

    mappings:
        ad_image:
            uri_prefix: /images/ads
            upload_destination: '%kernel.project_dir%/public/images/ads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: true
        user_image:
            uri_prefix: /images/user
            upload_destination: '%kernel.project_dir%/public/images/user'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: true
        ad_cover_image:
            uri_prefix: /images/ads_cover_images
            upload_destination: '%kernel.project_dir%/public/images/ads_cover_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: true


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
